# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:10:05+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint

from models import (
    PricingV2TrunkingCountryInstance,
    PricingV2TrunkingNumber,
    PricingV2VoiceVoiceCountryInstance,
    PricingV2VoiceVoiceNumber,
    V2TrunkingCountriesGetResponse,
    V2VoiceCountriesGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Pricing',
    version='1.42.0',
    servers=[{'url': 'https://pricing.twilio.com'}],
)


@app.get(
    '/v2/Trunking/Countries',
    tags=['trunking_country_management', 'voice_country_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_trunking_country(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/Trunking/Countries/{IsoCountry}',
    description=""" Fetch a specific Country. """,
    tags=['trunking_country_management', 'voice_country_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_trunking_country(iso_country: str = Path(..., alias='IsoCountry')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/Trunking/Numbers/{DestinationNumber}',
    description=""" Fetch pricing information for a specific destination and, optionally, origination phone number. """,
    tags=['trunking_number_management', 'voice_number_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_trunking_number(
    destination_number: str = Path(..., alias='DestinationNumber'),
    origination_number: Optional[str] = Query(None, alias='OriginationNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/Voice/Countries',
    tags=[
        'trunking_country_management',
        'trunking_number_management',
        'voice_country_management',
        'voice_number_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_voice_country(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/Voice/Countries/{IsoCountry}',
    description=""" Fetch a specific Country. """,
    tags=['trunking_country_management', 'voice_country_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_voice_country(iso_country: str = Path(..., alias='IsoCountry')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/Voice/Numbers/{DestinationNumber}',
    description=""" Fetch pricing information for a specific destination and, optionally, origination phone number. """,
    tags=['trunking_number_management', 'voice_number_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_voice_number(
    destination_number: str = Path(..., alias='DestinationNumber'),
    origination_number: Optional[str] = Query(None, alias='OriginationNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
