# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:10:05+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field


class PricingV2TrunkingCountry(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class OriginatingCallPrice(BaseModel):
    base_price: Optional[float] = None
    current_price: Optional[float] = None
    number_type: Optional[str] = None


class TerminatingPrefixPrice(BaseModel):
    base_price: Optional[float] = None
    current_price: Optional[float] = None
    destination_prefixes: Optional[List[str]] = None
    friendly_name: Optional[str] = None
    origination_prefixes: Optional[List[str]] = None


class PricingV2TrunkingCountryInstance(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).',
    )
    originating_call_prices: Optional[List[OriginatingCallPrice]] = Field(
        None,
        description='The list of [OriginatingCallPrice](https://www.twilio.com/docs/voice/pricing#inbound-call-price) records.',
    )
    price_unit: Optional[str] = Field(
        None,
        description='The currency in which prices are measured, specified in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format (e.g. `usd`, `eur`, `jpy`).',
    )
    terminating_prefix_prices: Optional[List[TerminatingPrefixPrice]] = Field(
        None,
        description='The list of [TerminatingPrefixPrice](https://www.twilio.com/docs/voice/pricing#outbound-prefix-price-with-origin) records.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class PricingV2TrunkingNumber(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    destination_number: Optional[str] = Field(
        None,
        description='The destination phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)',
    )
    originating_call_price: Optional[OriginatingCallPrice] = Field(
        None,
        description='The [OriginatingCallPrice](https://www.twilio.com/docs/voice/pricing#inbound-call-price) record.',
    )
    origination_number: Optional[str] = Field(
        None,
        description='The origination phone number in [[E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    price_unit: Optional[str] = Field(
        None,
        description='The currency in which prices are measured, specified in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format (e.g. `usd`, `eur`, `jpy`).',
    )
    terminating_prefix_prices: Optional[List[TerminatingPrefixPrice]] = None
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class PricingV2Voice(BaseModel):
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of the related Countries and Numbers resources.'
    )
    name: Optional[str] = Field(None, description='The resource name.')
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class PricingV2VoiceVoiceCountry(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class InboundCallPrice(BaseModel):
    base_price: Optional[float] = None
    current_price: Optional[float] = None
    number_type: Optional[str] = None


class OutboundPrefixPrice(BaseModel):
    base_price: Optional[float] = None
    current_price: Optional[float] = None
    destination_prefixes: Optional[List[str]] = None
    friendly_name: Optional[str] = None
    origination_prefixes: Optional[List[str]] = None


class PricingV2VoiceVoiceCountryInstance(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    inbound_call_prices: Optional[List[InboundCallPrice]] = Field(
        None,
        description='The list of [InboundCallPrice](https://www.twilio.com/docs/voice/pricing#inbound-call-price) records.',
    )
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).',
    )
    outbound_prefix_prices: Optional[List[OutboundPrefixPrice]] = Field(
        None,
        description='The list of [OutboundPrefixPriceWithOrigin](https://www.twilio.com/docs/voice/pricing#outbound-prefix-price-with-origin) records.',
    )
    price_unit: Optional[str] = Field(
        None,
        description='The currency in which prices are measured, specified in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format (e.g. `usd`, `eur`, `jpy`).',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class OutboundCallPrice(BaseModel):
    base_price: Optional[float] = None
    current_price: Optional[float] = None
    origination_prefixes: Optional[List[str]] = None


class PricingV2VoiceVoiceNumber(BaseModel):
    country: Optional[str] = Field(None, description='The name of the country.')
    destination_number: Optional[str] = Field(
        None,
        description='The destination phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    inbound_call_price: Optional[InboundCallPrice] = Field(
        None,
        description='The [InboundCallPrice](https://www.twilio.com/docs/voice/pricing#inbound-call-price) record.',
    )
    iso_country: Optional[str] = Field(
        None,
        description='The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)',
    )
    origination_number: Optional[str] = Field(
        None,
        description='The origination phone number in [[E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    outbound_call_prices: Optional[List[OutboundCallPrice]] = Field(
        None,
        description='The list of [OutboundCallPriceWithOrigin](https://www.twilio.com/docs/voice/pricing#outbound-call-price-with-origin) records.',
    )
    price_unit: Optional[str] = Field(
        None,
        description='The currency in which prices are measured, specified in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format (e.g. `usd`, `eur`, `jpy`).',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V2TrunkingCountriesGetResponse(BaseModel):
    countries: Optional[List[PricingV2TrunkingCountry]] = None
    meta: Optional[Meta] = None


class V2VoiceCountriesGetResponse(BaseModel):
    countries: Optional[List[PricingV2VoiceVoiceCountry]] = None
    meta: Optional[Meta] = None
